### ISSUE TITLE
Key bindings stopped working

### ISSUE THREAD

**Issue by dtgoitia** [shd101wyy/markdown-preview-enhanced#434]
Hi!

Few days ago the key binding `ctrl-shift-M` stopped working. The Key Binding Resolver showed me I was using the right key bind, and that the key bind exists and was associated to the desired command.

Editing the file `keymaps\markdown-preview-enhanced.cson` and changing the scope from `gfm` to `text` at line 10 worked for me.

before:
```cson
'atom-workspace atom-text-editor[data-grammar*="gfm"]':
```
after:
```cson
'atom-workspace atom-text-editor[data-grammar*="text"]':
```

I hope this helps :)

**Comment by shd101wyy** [comment]
@dtgoitia thanks, I will change it right away.

**Comment by shd101wyy** [comment]
@dtgoitia Can you help me check if this works?  
```
'atom-workspace, atom-workspace atom-text-editor':
  'ctrl-shift-m': 'markdown-preview:toggle'
```

**Comment by dtgoitia** [comment]
@shd101wyy Sorry, my late answer. I have just tested it and yes, it works fine for me :)

**Comment by dtgoitia** [comment]
@shd101wyy However, this will allow you to run the command 'markdown-preview-enhanced:toggle' from any scope, not just markdown.

I get this error when run the command in non-markdown files:
![image](https://cloud.githubusercontent.com/assets/21012855/26822478/1422dd5c-4aa2-11e7-8012-2eda97fa1e1f.png)

Using the scoped solution the command cannot be triggered outside markdown files, so no error.

Hope this helps! :)

**Comment by shd101wyy** [comment]
@dtgoitia should be fixed now.  
Cheers :)

**Comment by dtgoitia** [comment]
Sorry @shd101wyy , I still get this message when pressing `ctrl-shift-m`:
![image](https://user-images.githubusercontent.com/21012855/26964721-c79324c4-4cea-11e7-8252-a66a7fb8c5c8.png)
And the command doesn't show the preview view. I have only been able to make the preview work from the command palette :P

**Comment by shd101wyy** [comment]
What operating system are you using?

**Comment by dtgoitia** [comment]
Windows 10 x64

**Comment by cyranodesale** [comment]
Key bindings stopped for me too, using Windows 7 64... I tried the cson editing solution and still nothing happens. I don´t get any error messages though, it simply won´t give any responses to my insistent pressing of the key bindings to open preview.  o.O

**Comment by dtgoitia** [comment]
@cyranodesale 

This is the code I use for win7 x64 and atom 1.18.0.
```
'atom-workspace, atom-workspace atom-text-editor':
  'ctrl-shift-m': 'markdown-preview-enhanced:toggle'
  'ctrl-shift-i': 'markdown-preview-enhanced:image-helper'
  'shift-enter': 'markdown-preview-enhanced:run-code-chunk'
  'ctrl-shift-enter': 'markdown-preview-enhanced:run-all-code-chunks'
  'ctrl-shift-s': 'markdown-preview-enhanced:sync-preview'

'.platform-darwin atom-workspace .markdown-preview-enhanced-container':
  'cmd-+': 'markdown-preview-enhanced:zoom-in'
  'cmd-=': 'markdown-preview-enhanced:zoom-in'
  'cmd--': 'markdown-preview-enhanced:zoom-out'
  'cmd-_': 'markdown-preview-enhanced:zoom-out'
  'cmd-0': 'markdown-preview-enhanced:reset-zoom'
  'cmd-r': 'markdown-preview-enhanced:refresh-preview'
  'ctrl-shift-s': 'markdown-preview-enhanced:sync-source'

'.platform-win32 atom-workspace .markdown-preview-enhanced-container, .platform-linux atom-workspace .markdown-preview-enhanced-container':
  'ctrl-+': 'markdown-preview-enhanced:zoom-in'
  'ctrl-=': 'markdown-preview-enhanced:zoom-in'
  'ctrl--': 'markdown-preview-enhanced:zoom-out'
  'ctrl-_': 'markdown-preview-enhanced:zoom-out'
  'ctrl-0': 'markdown-preview-enhanced:reset-zoom'
  'ctrl-r': 'markdown-preview-enhanced:refresh-preview'
  'ctrl-shift-s': 'markdown-preview-enhanced:sync-source'
```

**Comment by cyranodesale** [comment]
Thanks for the try @dtgoitia , I tried this but when opening Atom it gave me an error message from the start when trying to start the preview-enhanced package. Then I once again tried to reinstall it, which of course reseted the keymap code to its standards. So, neither changing gfm to text nor your last updated code worked for me so far. Here´s the original code (beginning from line 10 where I changed gfm to text and, as it didn´t work, I changed back to gfm):
```
'.platform-win32 atom-workspace atom-text-editor[data-grammar="source gfm"], .platform-linux atom-workspace atom-text-editor[data-grammar="source gfm"], .platform-darwin atom-workspace atom-text-editor[data-grammar="source gfm"]':
  'ctrl-shift-m': 'markdown-preview-enhanced:toggle'
  'ctrl-shift-i': 'markdown-preview-enhanced:image-helper'
  'shift-enter': 'markdown-preview-enhanced:run-code-chunk'
  'ctrl-shift-enter': 'markdown-preview-enhanced:run-all-code-chunks'
  'ctrl-shift-s': 'markdown-preview-enhanced:sync-preview'

'.platform-darwin atom-workspace .markdown-preview-enhanced-container':
  'cmd-+': 'markdown-preview-enhanced:zoom-in'
  'cmd-=': 'markdown-preview-enhanced:zoom-in'
  'cmd--': 'markdown-preview-enhanced:zoom-out'
  'cmd-_': 'markdown-preview-enhanced:zoom-out'
  'cmd-0': 'markdown-preview-enhanced:reset-zoom'
  'cmd-r': 'markdown-preview-enhanced:refresh-preview'
  'ctrl-shift-s': 'markdown-preview-enhanced:sync-source'

'.platform-win32 atom-workspace .markdown-preview-enhanced-container, .platform-linux atom-workspace .markdown-preview-enhanced-container':
  'ctrl-+': 'markdown-preview-enhanced:zoom-in'
  'ctrl-=': 'markdown-preview-enhanced:zoom-in'
  'ctrl--': 'markdown-preview-enhanced:zoom-out'
  'ctrl-_': 'markdown-preview-enhanced:zoom-out'
  'ctrl-0': 'markdown-preview-enhanced:reset-zoom'
  'ctrl-r': 'markdown-preview-enhanced:refresh-preview'
  'ctrl-shift-s': 'markdown-preview-enhanced:sync-source'```

**Comment by cyranodesale** [comment]
@dtgoitia , my mistake! Your code works. I was using 32, not 64 version of Atom 1.18.0 . :|

Now your last code worked just fine and I got my nice hotkey working again. Thanks!
