### ISSUE TITLE
"Create ToC" not working

### ISSUE THREAD

**Issue by werunom** [shd101wyy/markdown-preview-enhanced#508]
Hi. 
Using this package in atom (linux). After the new update, the insertion of table of contents is not working. When I use the command `Create ToC` in the command pallette, only the below line is appended - 

`<!-- @import "[TOC]" {cmd:"toc", depthFrom:1, depthTo:6, orderedList:false} -->`

Headings are not generated below the above insertion. 

Let me know if you need more details. Thanks for this great package!

**Comment by shd101wyy** [comment]
The TOC will be updated when you save the file.

**Comment by werunom** [comment]
I had tried that and nothing happened. 
Am I missing something or not doing right?

**Comment by shd101wyy** [comment]
Oh that's weird. I don't have Linux so I am not able to test it. Can you
open developer tool and see if there are any error messages appeared in the
console?

Also please send me your markdown file if you can. I will have a look this
weekend probably.

And you can help me try the vscode version to test if that issue also
happened.

Thanks

**Comment by werunom** [comment]
I tried the following - 
1. Used the "create ToC" command
2. Opened the preview and clicked on the first symbol
3. This opened the side bar having the ToC

Is this what you are suggesting? if yes, then this is working fine. 

I got alarmed because I was expecting the previous functionality - where the toc is embedded right into the md/txt file. Looks like in this updated package, toc is something which is visible only in the preview.  Am I right?

But, if I can vote and suggest, can you still keep the functionality to embed the toc? I was using this functionality a lot. Having embedded toc is useful for long notes.

**Comment by shd101wyy** [comment]
The embeded TOC should be inserted to your markdown file when you save the
markdown file. So I think it's a bug now. It works fine on my Mac and
Windows though.

**Comment by werunom** [comment]
Oh! Glad to know that this functionality is still present.

Will wait for the fix. Thanks again.

**Comment by zk4** [comment]
got the same issue  on Mac.
mpe  0.14.2
atom 1.18.0

**Comment by Niefee** [comment]
@shd101wyy 我用MAC保存的时候不能自动生成TOC导航啊，window却可以。都是升级到最新版，

**Comment by shd101wyy** [comment]
@werunom @Niefee Fixed now. Thanks :)

**Comment by werunom** [comment]
@shd101wyy - Updated the package. But, still the issue persists. When I use the command-pallette command to insert toc, the following line is inserted 
`<!-- @import "[TOC]" {cmd:"toc", depthFrom:1, depthTo:6, orderedList:false} -->`

Nothing else happens on save. Toc is not embedded.

**Comment by shd101wyy** [comment]
Can you toggle developer tool and send me a screenshot of console?

**Comment by werunom** [comment]
In the console of the developer tool, nothing rolled when I inserted the toc. In any case, I am attaching the screenshot for reference...
![screenshot_20170724_135922](https://user-images.githubusercontent.com/24664855/28514660-7b26c260-7078-11e7-998d-a863d4b51c8c.png)
I have done it right - the way you wanted it? Let me know if you need something else...

**Comment by shd101wyy** [comment]
You need to open preview first before you use the create TOC command.
Could you please send me a gif showing how you operate?

**Comment by werunom** [comment]
@shd101wyy  - I had done the same - keep the console open. Then in couple of markdown files I executed the following steps - 1) insert toc using command pallette 2) save the file and 3) open the markdown-preview
Only in the step (3), the console logs the below comments - 
```
webview:  %c 01:13:23 (410) :%cDEBUG: 
preview-content-provider.js:224 webview:  init webview: /home/Research/Notes/Philosophy Readings/Philosophy of Science/Scientific objects.txt
preview-content-provider.js:224 webview:  %c 01:13:23 (409) :%cDEBUG: 
```
Apart from that nothing else comes up in the console. I will try to post the gif in sometime...

**Comment by shd101wyy** [comment]
@werunom Try:
1. Open Markdown Preview first. 
2. Save your markdown file.  

From your description, you saved the markdown file before you opened the preview.

**Comment by werunom** [comment]
Finally! Thanks for pointing the right steps. Got the toc embedded. :)

Closing the issue...

**Comment by YimianDai** [comment]
> @werunom Try:
> 
> 1. Open Markdown Preview first.
> 2. Save your markdown file.
> 
> From your description, you saved the markdown file before you opened the preview.

Thanks. It works for me.
