### ISSUE TITLE
Preview pane steals focus

### ISSUE THREAD

**Issue by danielbayley** [shd101wyy/markdown-preview-enhanced#615]
Toggling preview is stealing focus from the current editor, which is annoying, especially when dipping in and out of various Markdown files…

I think this is a regression, as I don't recall it happening prior to the latest update or so.

macOS 10.12.6
Atom 1.20.0-beta6
markdown-preview-enhanced 0.14.10

**Comment by shd101wyy** [comment]
It might be because you are using atom beta. I will check when I have time.
Thanks.

**Comment by danielbayley** [comment]
Yeah could be, although I've been using beta exclusively for quite a while.

**Comment by shd101wyy** [comment]
So you want when you open the preview, the editor should be focused instead
of the preview. Am I right?

**Comment by danielbayley** [comment]
@shd101wyy Yeah, it shouldn't steal focus from the editor.

**Comment by shd101wyy** [comment]
@danielbayley Fixed now. Cheers :)

**Comment by danielbayley** [comment]
@shd101wyy Tested and working. Thanks! 😎

**Comment by ddamasceno** [comment]
I am still having problem with this :  

When I want to rename a file from the Tree View, the automatic preview steels the focus and I am unable to use F2 shortcut to quickly rename the file.

When I disable the package everything goes fine.

I am using Atom 1.26.1 and Markdown Preview Enhanced 0.15.8
