### ISSUE TITLE
Atom crashes if a change in settings is made while the preview is open.

### ISSUE THREAD

**Issue by gvgramazio** [shd101wyy/markdown-preview-enhanced#692]
Atom crashes if a change in settings is made while the preview is open. If the preview is closed the change can be made without any problem.

**Comment by shd101wyy** [comment]
That's weird. I will have a look when I have time. Thanks.

**Comment by gvgramazio** [comment]
Until now this happens for almost all settings. I tried to modify style.less for custom CSS and the same thing happenes: if the preview is closed there is no problem, if the preview is open atom unexpectedly closes. I don't know if it's a real crash because windows doesn't notify me any crash.

P.S. I really love your package, you did a very good job.

**Comment by shd101wyy** [comment]
I would assume there might be package conflicts? Try disabling some other packages.  
Also, open developer tool and check if there is any error occurred in the javascript console.

Thanks

**Comment by gvgramazio** [comment]
I checked with dev tool and there are no errors before I change the settings. I don't think that there are package conflicts because I disabled everything except your package. But there is a strange thing that I didn't notice before: the error happens only if the preview is open **and** if it is not visible. I mean that if I split the screen in order to have both the settings and the preview visible, there are no errors at all when I change the settings. Also, I have this error only in windows while with Ubuntu there are no problems.

**Comment by shd101wyy** [comment]
Ok I see. Mine also crashed on Windows. 
Let me try to fix it...

**Comment by shd101wyy** [comment]
Huhhh I couldn't trigger that bug anymore.

**Comment by shd101wyy** [comment]
Ok I see. 
If I have file `a.md` and file `b.md`. 
I open preview for `a.md`, then I move `b.md` to the pane of the preview, atom will crash.

**Comment by shd101wyy** [comment]
@gvgramazio Fixed now. Thanks.

**Comment by gvgramazio** [comment]
I updated your package to 0.15.1 but the error is still there. Is the fix in that update?

I know that I've already wrote how to trigger the error but I rewrite here just to be sure that you are able to trigger it as well:
- open atom with your package enabled
- open a .md file and its preview
- open the package settings page and change something

**If** the settings page is visible but the preview is **not** visible then atom crashes, **else if** both the settings page and the preview are visible then everything is ok and atom doesn't crash.

**Comment by shd101wyy** [comment]
@gvgramazio I will look into that next weekend. Thanks.
