### ISSUE TITLE
Extension (VS code) does not properly work on my windows machine

### ISSUE THREAD

**Issue by DougHeffernan** [shd101wyy/markdown-preview-enhanced#798]
Hello,
i really like to use your great extension in VS code. However i have the problem, that i can't get it running properly. The basic Markdown preview is working just fine. Also things like including images. 
But math expressions (using Mathjax or KaTex) or plantuml diagrams won't be rendered.
PlantUml: I checked the plantuml.jar and run it from command line, it did work. 
Mathjax:  When i run the test.html it looks already wrong.
I guess i just made a mistake using it but i can't figure out what i did wrong.

Would be great to get it running, since it would be a huge benefit for my work.
Best regards,
Daniel

**Comment by rubberduck203** [comment]
I don't think it's you Daniel.
Math preview doesn't work for me either.

**Comment by shd101wyy** [comment]
The MathJax issue should be fixed now. But I am not sure about the PlantUML one. Could you please send me your markdown file? Thank you.

**Comment by DougHeffernan** [comment]
Hey 
thank you for your response. 
Unfortunately it still does not work. Is there something i need to do when installing the extension. I installed it using the extension manager in VS Code.

Here would be a test.markdown which does not work:
# Test regarding Issue \#798

# 1. Mathematical equations
The following is a formula which is not rendered:
$$ \varphi_{Az}=\frac{2\pi}{N_{beams}}B_{BF,m} $$

# 2. Plantuml
The following is a plantuml diagram which is not rendered:
```puml
@startuml
title test

start
if (Is first run?) then (yes)
    :Do_First_Things_First()|
else (no)
    :Do_Something()|
endif
if (Ready?) then (yes)
    :Clean_Up()|
else (no)
    :Do_Something_Else()|
endif

stop
@enduml
```

**Comment by shd101wyy** [comment]
@DougHeffernan I just tried it on my Windows 10 machine and it worked well.  

![capture](https://user-images.githubusercontent.com/1908863/37218446-110aadee-2386-11e8-8ce1-bd79beae2c28.PNG)

Are you using the newest version of vscode? Thank you.

**Comment by shd101wyy** [comment]
No problem. Glad to help.
